/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_books_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{gutenberg_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata */
        get: operations["metadata_api_v1_books__gutenberg_id__metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{gutenberg_id}/epub-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Epub Url */
        get: operations["epub_url_api_v1_books__gutenberg_id__epub_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/gutenberg/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Gutenberg Book
         * @description Idempotently register a Gutenberg book in the public catalog and add
         *     it to the user's library. Returns the book row.
         */
        post: operations["register_gutenberg_book_api_v1_books_gutenberg_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Progress */
        put: operations["update_progress_api_v1_books__book_id__progress_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/captured-words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Captured Words
         * @description Words captured in this book by this user, with frequency and
         *     first-seen timestamp. Used by the reader to color words and animate
         *     newly-discovered ones.
         */
        get: operations["list_captured_words_api_v1_books__book_id__captured_words_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Captures */
        get: operations["list_captures_api_v1_captures_get"];
        put?: never;
        /** Create Capture */
        post: operations["create_capture_api_v1_captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures/{capture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Capture */
        put: operations["update_capture_api_v1_captures__capture_id__put"];
        post?: never;
        /** Delete Capture */
        delete: operations["delete_capture_api_v1_captures__capture_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictionary/{word}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Word */
        get: operations["lookup_word_api_v1_dictionary__word__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookOut */
        BookOut: {
            /** Id */
            id: string;
            /** Book Hash */
            book_hash: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "gutenberg" | "fs" | "drive" | "dropbox";
            /** Source Ref */
            source_ref: string;
            /** Title */
            title: string;
            /** Author */
            author: string | null;
            /** Language */
            language: string | null;
            /** Is Public */
            is_public: boolean;
        };
        /** CaptureCreate */
        CaptureCreate: {
            /** Word */
            word: string;
            /** Context Sentence */
            context_sentence?: string | null;
            /** Page Or Location */
            page_or_location?: string | null;
            /** Book Id */
            book_id?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Tags */
            tags?: string[];
        };
        /** CaptureOut */
        CaptureOut: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Word */
            word: string;
            /** Word Normalized */
            word_normalized: string;
            /** Context Sentence */
            context_sentence: string | null;
            /** Page Or Location */
            page_or_location: string | null;
            /** Book Id */
            book_id: string | null;
            /** Tags */
            tags: string[];
            /** Promoted To Card */
            promoted_to_card: boolean;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Translation */
            translation?: string | null;
            /** Definition */
            definition?: string | null;
            /** Ipa */
            ipa?: string | null;
            /** Audio Url */
            audio_url?: string | null;
            /** Examples */
            examples?: string[];
        };
        /** CaptureUpdate */
        CaptureUpdate: {
            /** Context Sentence */
            context_sentence?: string | null;
            /** Page Or Location */
            page_or_location?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** CapturedWord */
        CapturedWord: {
            /** Word Normalized */
            word_normalized: string;
            /** Count */
            count: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
        };
        /** DictionaryEntry */
        DictionaryEntry: {
            /** Word Normalized */
            word_normalized: string;
            /** Language */
            language: string;
            /** Translation */
            translation: string | null;
            /** Definition */
            definition: string | null;
            /** Ipa */
            ipa: string | null;
            /** Audio Url */
            audio_url: string | null;
            /** Examples */
            examples?: string[];
            /** Source */
            source: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Cache Status */
            cache_status: string;
        };
        /** GutenbergRegisterRequest */
        GutenbergRegisterRequest: {
            /** Gutenberg Id */
            gutenberg_id: number;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProgressUpdateRequest */
        ProgressUpdateRequest: {
            /**
             * Location
             * @description EPUB CFI or page number string
             */
            location: string;
            /** Percent */
            percent: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_books_search_get: {
        parameters: {
            query: {
                q: string;
                page?: number;
            };
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metadata_api_v1_books__gutenberg_id__metadata_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                gutenberg_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    epub_url_api_v1_books__gutenberg_id__epub_url_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                gutenberg_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_gutenberg_book_api_v1_books_gutenberg_register_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GutenbergRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_progress_api_v1_books__book_id__progress_put: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_captured_words_api_v1_books__book_id__captured_words_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapturedWord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_captures_api_v1_captures_get: {
        parameters: {
            query?: {
                book_id?: string | null;
                promoted?: boolean | null;
                tag?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_capture_api_v1_captures_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_capture_api_v1_captures__capture_id__put: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_capture_api_v1_captures__capture_id__delete: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_word_api_v1_dictionary__word__get: {
        parameters: {
            query?: {
                language?: string;
            };
            header: {
                authorization: string;
            };
            path: {
                word: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
